### ISSUE TITLE
Use rustc's lexer

### ISSUE THREAD

**Issue by bjorn3** [tuqqu/oxide-lang#10]
It is independent of the rest of rustc, used by rust-analyzer and available as rustc-ap-rustc_lexer on crates.io. Using rustc's lexer may save a bit on code maintenance and will make oxide's syntax a bit closer to rust's.

**Comment by tuqqu** [comment]
Hello. Thank you for your interest in this project. 
It was made as zero dependency and, to be honest, lexer is rather trivial, however your proposal is fair. It's best to leave it as is.

**Comment by bjorn3** [comment]
Makes sense.
